import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import toast, { Toaster } from 'react-hot-toast';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <GoogleOAuthProvider clientId="266029738854-nk7j0e5c1tr7rd65lptgocug2sb91iti.apps.googleusercontent.com">
      <body className={inter.className}>{children}</body>
      <Toaster />
      </GoogleOAuthProvider>
    </html>
  );
}
